name: generics-sop-lens
version: 0.1.2.0
synopsis: Lenses for types in generics-sop
description: Lenses for types in generics-sop package
author: Oleg Grenrus <oleg.grenrus@iki.fi>
maintainer: Oleg Grenrus <oleg.grenrus@iki.fi>
license: BSD3
github: phadej/generics-sop-lens
category: Web
tested-with: GHC==7.8.4, GHC==7.10.3, GHC==8.0.1
extra-source-files:
- README.md
- CHANGELOG.md

ghc-options: -Wall

dependencies:
  - base                  >=4.7      && <4.10
  - generics-sop          >=0.1      && <0.3
  - lens                  >=4.7      && <4.16

library:
  source-dirs: src
